plugins:
  discourse_jira_enabled:
    default: false
    client: true
  discourse_jira_url:
    default: ""
  discourse_jira_username:
    default: ""
  discourse_jira_password:
    default: ""
    secret: true
  discourse_jira_webhook_token:
    default: ""
    secret: true
  discourse_jira_verbose_log:
    default: false
  discourse_jira_api_version:
    default: 0
    hidden: true
  discourse_jira_close_topic_on_resolve:
    default: false
  discourse_jira_add_fields_to_default_screen:
    default: false
