plugins:
  discourse_jira_enabled:
    default: false
    client: true
  discourse_jira_url:
    default: ""
  discourse_jira_username:
    default: ""
  discourse_jira_password:
    default: ""
    secret: true
  discourse_jira_webhook_token:
    default: ""
    secret: true
  discourse_jira_verbose_log:
    default: false
  discourse_jira_api_version:
    default: 0
    hidden: true
  discourse_jira_close_topic_on_resolve:
    default: false
  discourse_jira_sync_issue_comments:
    default: false
  discourse_jira_issue_tags_enabled:
    default: false
  discourse_jira_allowed_groups:
    default: "1" # @admins
    mandatory_values: "1"
    type: group_list
    client: true
    allow_any: false
    refresh: true
    validator: "AtLeastOneGroupValidator"
